// ci:loc-ok — Phase 2 multi-CRD reconciler / generated module; intentional. Tracked in plan.md §S15 follow-up.
//! K8s AI Conformance v1.35+ test suite for AzureClaw.
//!
//! See `tests/cncf-conformance/README.md` for the criterion list. The
//! suite is intentionally **manifest-driven**: it walks the rendered
//! Helm templates under `deploy/helm/azureclaw/templates/` and asserts
//! shape invariants without requiring a running K8s cluster. This
//! keeps PR CI fast and side-effect-free; the same suite can also be
//! invoked against `kustomize`-rendered or `helm template`-rendered
//! output in a kind cluster (Phase 3 deliverable).
//!
//! Public entry points:
//!
//! - [`load_repo_manifests`] — discover all `*.yaml` under the helm
//!   templates dir and parse each into a list of `serde_yaml::Value`
//!   documents (multi-doc YAML aware).
//! - [`run_all_checks`] — apply every conformance criterion to the
//!   loaded manifest set and return a [`ConformanceReport`].

#![deny(clippy::all)]

use std::collections::BTreeMap;
use std::path::PathBuf;

use serde::Deserialize;
use serde_yaml::Value;

/// Outcome of a single conformance criterion.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Outcome {
    Pass,
    Fail(String),
}

impl Outcome {
    pub fn is_pass(&self) -> bool {
        matches!(self, Outcome::Pass)
    }
}

/// One row in the report — a CNCF criterion paired with its result.
#[derive(Debug, Clone)]
pub struct CheckResult {
    pub id: &'static str,
    pub criterion: &'static str,
    pub outcome: Outcome,
}

/// Aggregate report. `pass` / `fail` counts derive from `results`.
#[derive(Debug, Clone, Default)]
pub struct ConformanceReport {
    pub results: Vec<CheckResult>,
}

impl ConformanceReport {
    pub fn pass_count(&self) -> usize {
        self.results.iter().filter(|r| r.outcome.is_pass()).count()
    }

    pub fn fail_count(&self) -> usize {
        self.results.len() - self.pass_count()
    }

    pub fn all_passed(&self) -> bool {
        self.fail_count() == 0
    }

    /// Render the markdown report consumed by
    /// `tests/cncf-conformance/CONFORMANCE-REPORT.md`. Stable order
    /// (insertion order); stable formatting so a regenerated report
    /// produces a reproducible diff.
    pub fn to_markdown(&self) -> String {
        let mut out = String::new();
        out.push_str("# AzureClaw — CNCF K8s AI Conformance Report\n\n");
        out.push_str(
            "Generated by `cargo run -p azureclaw-cncf-conformance --bin cncf-conformance`.\n\n",
        );
        out.push_str(&format!(
            "**Status:** {} / {} criteria pass.\n\n",
            self.pass_count(),
            self.results.len()
        ));
        out.push_str("| ID | Criterion | Result |\n");
        out.push_str("|----|-----------|--------|\n");
        for r in &self.results {
            let (mark, detail) = match &r.outcome {
                Outcome::Pass => ("✅", String::new()),
                Outcome::Fail(msg) => ("❌", format!(" — {msg}")),
            };
            out.push_str(&format!(
                "| {} | {} | {}{} |\n",
                r.id, r.criterion, mark, detail
            ));
        }
        out
    }
}

/// Resolve the repository root.
pub fn repo_root() -> PathBuf {
    // CARGO_MANIFEST_DIR points at tests/cncf-conformance/.
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(|p| p.parent())
        .map(|p| p.to_path_buf())
        .unwrap_or(manifest)
}

/// All Helm template manifests, grouped by source file. The Helm
/// chart is rendered with `helm template` so multi-doc, conditional,
/// and value-templated content all parse as plain YAML. If `helm`
/// is not on PATH the loader falls back to parsing the static
/// `crd*.yaml` set under `deploy/helm/azureclaw/templates/` (CRDs
/// have no Helm tokens) — this keeps the conformance checks that
/// only need CRD shape running on minimal envs.
pub fn load_repo_manifests() -> BTreeMap<PathBuf, Vec<Value>> {
    let root = repo_root();
    let mut out = BTreeMap::new();

    if let Some(text) = render_helm(&root) {
        // `helm template` output is one big multi-doc YAML stream
        // with `# Source: ...` comments separating each rendered
        // file. Group by source so the per-path BTreeMap stays
        // meaningful (some checks key on path).
        for (source, body) in split_by_source(&text) {
            let key = root.join(source);
            let docs: Vec<Value> = serde_yaml::Deserializer::from_str(&body)
                .filter_map(|d| Value::deserialize(d).ok())
                .filter(|v| !v.is_null())
                .collect();
            if !docs.is_empty() {
                out.entry(key).or_insert_with(Vec::new).extend(docs);
            }
        }
        return out;
    }

    // Fallback path — only the static CRD YAMLs.
    let dir = root.join("deploy/helm/azureclaw/templates");
    if !dir.exists() {
        return out;
    }
    for entry in walkdir::WalkDir::new(&dir).into_iter().flatten() {
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        let name = path.file_name().and_then(|s| s.to_str()).unwrap_or("");
        if !(name.starts_with("crd") && name.ends_with(".yaml")) {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(path) else {
            continue;
        };
        let docs: Vec<Value> = serde_yaml::Deserializer::from_str(&text)
            .filter_map(|d| Value::deserialize(d).ok())
            .filter(|v| !v.is_null())
            .collect();
        if !docs.is_empty() {
            out.insert(path.to_path_buf(), docs);
        }
    }
    out
}

fn render_helm(root: &std::path::Path) -> Option<String> {
    let chart = root.join("deploy/helm/azureclaw");
    if !chart.exists() {
        return None;
    }
    let output = std::process::Command::new("helm")
        .arg("template")
        .arg("ac")
        .arg(&chart)
        .arg("--namespace")
        .arg("azureclaw-system")
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    String::from_utf8(output.stdout).ok()
}

fn split_by_source(rendered: &str) -> Vec<(String, String)> {
    let mut out: Vec<(String, String)> = Vec::new();
    let mut current_source = String::from("unknown");
    let mut buf = String::new();
    for line in rendered.lines() {
        if line.starts_with("---") {
            if !buf.trim().is_empty() {
                out.push((current_source.clone(), std::mem::take(&mut buf)));
            }
            continue;
        }
        if let Some(s) = line.strip_prefix("# Source: ") {
            current_source = s.trim().to_string();
            continue;
        }
        buf.push_str(line);
        buf.push('\n');
    }
    if !buf.trim().is_empty() {
        out.push((current_source, buf));
    }
    out
}

/// All CRD documents across the loaded manifests.
pub fn collect_crds(manifests: &BTreeMap<PathBuf, Vec<Value>>) -> Vec<&Value> {
    let mut crds = Vec::new();
    for docs in manifests.values() {
        for d in docs {
            if d.get("kind").and_then(Value::as_str) == Some("CustomResourceDefinition") {
                crds.push(d);
            }
        }
    }
    crds
}

fn crd_kind(crd: &Value) -> Option<&str> {
    crd.get("spec")?.get("names")?.get("kind")?.as_str()
}

fn crd_versions(crd: &Value) -> Vec<&Value> {
    crd.get("spec")
        .and_then(|s| s.get("versions"))
        .and_then(Value::as_sequence)
        .map(|v| v.iter().collect())
        .unwrap_or_default()
}

fn version_schema(version: &Value) -> Option<&Value> {
    version.get("schema")?.get("openAPIV3Schema")
}

// ─── Individual checks ──────────────────────────────────────────────

/// C1 — every CRD declares at least one served + storage version.
pub fn check_crd_versions_served(crds: &[&Value]) -> Outcome {
    let mut missing = Vec::new();
    for c in crds {
        let kind = crd_kind(c).unwrap_or("?");
        let mut has_served = false;
        let mut has_storage = false;
        for v in crd_versions(c) {
            if v.get("served").and_then(Value::as_bool) == Some(true) {
                has_served = true;
            }
            if v.get("storage").and_then(Value::as_bool) == Some(true) {
                has_storage = true;
            }
        }
        if !(has_served && has_storage) {
            missing.push(kind.to_string());
        }
    }
    if missing.is_empty() {
        Outcome::Pass
    } else {
        Outcome::Fail(format!("CRDs missing served/storage version: {missing:?}"))
    }
}

/// C2 — every CRD has at least one `additionalPrinterColumns` entry.
pub fn check_printer_columns(crds: &[&Value]) -> Outcome {
    let mut missing = Vec::new();
    for c in crds {
        let kind = crd_kind(c).unwrap_or("?");
        let any = crd_versions(c).iter().any(|v| {
            v.get("additionalPrinterColumns")
                .and_then(Value::as_sequence)
                .map(|s| !s.is_empty())
                .unwrap_or(false)
        });
        if !any {
            missing.push(kind.to_string());
        }
    }
    if missing.is_empty() {
        Outcome::Pass
    } else {
        Outcome::Fail(format!("CRDs without printer columns: {missing:?}"))
    }
}

/// C3 — every CRD `status` schema declares a `conditions` array.
pub fn check_conditions_array(crds: &[&Value]) -> Outcome {
    let mut missing = Vec::new();
    for c in crds {
        let kind = crd_kind(c).unwrap_or("?");
        let mut found = false;
        for v in crd_versions(c) {
            let Some(schema) = version_schema(v) else {
                continue;
            };
            let Some(props) = schema.get("properties") else {
                continue;
            };
            let Some(status) = props.get("status") else {
                continue;
            };
            let Some(status_props) = status.get("properties") else {
                continue;
            };
            if let Some(conditions) = status_props.get("conditions")
                && conditions.get("type").and_then(Value::as_str) == Some("array")
            {
                found = true;
                break;
            }
        }
        if !found {
            missing.push(kind.to_string());
        }
    }
    if missing.is_empty() {
        Outcome::Pass
    } else {
        Outcome::Fail(format!("CRDs without status.conditions[]: {missing:?}"))
    }
}

/// C4 — every CRD's `spec` schema is structural (no
/// `x-kubernetes-preserve-unknown-fields: true` at the spec root).
pub fn check_structural_schema(crds: &[&Value]) -> Outcome {
    let mut leaks = Vec::new();
    for c in crds {
        let kind = crd_kind(c).unwrap_or("?");
        for v in crd_versions(c) {
            let Some(schema) = version_schema(v) else {
                continue;
            };
            // Reject preserve-unknown-fields at spec root — it disables
            // structural-schema enforcement and is forbidden by the
            // CNCF criterion. Sub-tree usage (e.g. for a free-form
            // metadata blob) is allowed.
            let Some(spec) = schema.get("properties").and_then(|p| p.get("spec")) else {
                continue;
            };
            if spec
                .get("x-kubernetes-preserve-unknown-fields")
                .and_then(Value::as_bool)
                == Some(true)
            {
                leaks.push(kind.to_string());
            }
        }
    }
    if leaks.is_empty() {
        Outcome::Pass
    } else {
        Outcome::Fail(format!(
            "CRDs with non-structural spec (preserveUnknownFields=true): {leaks:?}"
        ))
    }
}

/// C5 — every CRD ships at least one `x-kubernetes-validations` (CEL)
/// rule somewhere in its schema tree.
pub fn check_cel_validations(crds: &[&Value]) -> Outcome {
    fn walk(v: &Value) -> bool {
        if let Some(map) = v.as_mapping() {
            if map.contains_key(Value::String("x-kubernetes-validations".into())) {
                return true;
            }
            for val in map.values() {
                if walk(val) {
                    return true;
                }
            }
        } else if let Some(seq) = v.as_sequence() {
            for val in seq {
                if walk(val) {
                    return true;
                }
            }
        }
        false
    }
    let mut missing = Vec::new();
    for c in crds {
        let kind = crd_kind(c).unwrap_or("?");
        if !walk(c) {
            missing.push(kind.to_string());
        }
    }
    if missing.is_empty() {
        Outcome::Pass
    } else {
        Outcome::Fail(format!("CRDs without CEL validations: {missing:?}"))
    }
}

/// C6 — every CRD declares a status subresource so reconcilers can
/// patch status without bumping `metadata.resourceVersion`.
pub fn check_status_subresource(crds: &[&Value]) -> Outcome {
    let mut missing = Vec::new();
    for c in crds {
        let kind = crd_kind(c).unwrap_or("?");
        let any = crd_versions(c).iter().any(|v| {
            v.get("subresources")
                .and_then(|s| s.get("status"))
                .is_some()
        });
        if !any {
            missing.push(kind.to_string());
        }
    }
    if missing.is_empty() {
        Outcome::Pass
    } else {
        Outcome::Fail(format!("CRDs without status subresource: {missing:?}"))
    }
}

/// C7 — every Deployment has both liveness + readiness probes.
pub fn check_deployment_probes(manifests: &BTreeMap<PathBuf, Vec<Value>>) -> Outcome {
    let mut missing: Vec<String> = Vec::new();
    for docs in manifests.values() {
        for d in docs {
            if d.get("kind").and_then(Value::as_str) != Some("Deployment") {
                continue;
            }
            let name = d
                .get("metadata")
                .and_then(|m| m.get("name"))
                .and_then(Value::as_str)
                .unwrap_or("?")
                .to_string();
            let containers = d
                .get("spec")
                .and_then(|s| s.get("template"))
                .and_then(|t| t.get("spec"))
                .and_then(|s| s.get("containers"))
                .and_then(Value::as_sequence);
            let Some(containers) = containers else {
                missing.push(format!("{name} (no containers)"));
                continue;
            };
            for c in containers {
                let cname = c
                    .get("name")
                    .and_then(Value::as_str)
                    .unwrap_or("?")
                    .to_string();
                let has_liveness = c.get("livenessProbe").is_some();
                let has_readiness = c.get("readinessProbe").is_some();
                if !(has_liveness && has_readiness) {
                    missing.push(format!("{name}/{cname}"));
                }
            }
        }
    }
    if missing.is_empty() {
        Outcome::Pass
    } else {
        Outcome::Fail(format!(
            "Deployments missing liveness/readiness: {missing:?}"
        ))
    }
}

/// C8 — operator namespace has a default-deny NetworkPolicy applied.
pub fn check_default_deny_netpol(manifests: &BTreeMap<PathBuf, Vec<Value>>) -> Outcome {
    for docs in manifests.values() {
        for d in docs {
            if d.get("kind").and_then(Value::as_str) != Some("NetworkPolicy") {
                continue;
            }
            let ns = d
                .get("metadata")
                .and_then(|m| m.get("namespace"))
                .and_then(Value::as_str)
                .unwrap_or("");
            // Accept either the literal `azureclaw-system` namespace
            // or any policy whose name starts with `default-deny`
            // (Helm renders `{{ .Release.Namespace }}` to the
            // operator install namespace).
            let name = d
                .get("metadata")
                .and_then(|m| m.get("name"))
                .and_then(Value::as_str)
                .unwrap_or("");
            let is_system = ns == "azureclaw-system" || ns.is_empty();
            if !is_system {
                continue;
            }
            let policy_types = d
                .get("spec")
                .and_then(|s| s.get("policyTypes"))
                .and_then(Value::as_sequence);
            let pod_selector_empty = d
                .get("spec")
                .and_then(|s| s.get("podSelector"))
                .map(|ps| {
                    ps.as_mapping()
                        .map(|m| {
                            m.is_empty()
                                || m.get(Value::String("matchLabels".into()))
                                    .and_then(Value::as_mapping)
                                    .map(|x| x.is_empty())
                                    .unwrap_or(false)
                        })
                        .unwrap_or(false)
                })
                .unwrap_or(false);
            let covers_egress_ingress = policy_types
                .map(|s| {
                    let names: Vec<&str> = s.iter().filter_map(Value::as_str).collect();
                    names.contains(&"Egress") && names.contains(&"Ingress")
                })
                .unwrap_or(false);
            if pod_selector_empty && covers_egress_ingress {
                return Outcome::Pass;
            }
            // Tolerate the legacy explicit-name convention as a hint.
            let _ = name;
        }
    }
    Outcome::Fail("no default-deny NetworkPolicy found in azureclaw-system".into())
}

/// C9 — every image reference declares an explicit tag or digest.
/// Untagged refs (which implicitly resolve to `:latest`) are
/// forbidden because they make rollbacks ambiguous. The AzureClaw
/// repo convention pins `:latest` as the *explicit* default tag for
/// controller / inference-router / sandbox images (see
/// `docs/operations/supply-chain.md`); production deployments are
/// expected to override the tag at install time with a digest pin
/// or a chart-`appVersion`-derived tag. This check enforces the
/// minimum bar — no implicit-:latest images — without conflicting
/// with the repo convention.
pub fn check_image_pinning(manifests: &BTreeMap<PathBuf, Vec<Value>>) -> Outcome {
    let mut bad = Vec::new();
    for (path, docs) in manifests {
        for d in docs {
            if d.get("kind").and_then(Value::as_str) != Some("Deployment") {
                continue;
            }
            let containers = d
                .get("spec")
                .and_then(|s| s.get("template"))
                .and_then(|t| t.get("spec"))
                .and_then(|s| s.get("containers"))
                .and_then(Value::as_sequence);
            let Some(containers) = containers else {
                continue;
            };
            for c in containers {
                let Some(image) = c.get("image").and_then(Value::as_str) else {
                    continue;
                };
                // Image must contain either `:` (tag) or `@` (digest).
                // Strip the registry host (everything before the first `/`)
                // so a hostname like `localhost:5000/foo` doesn't false-pass.
                let after_host = image.rsplit_once('/').map(|(_, r)| r).unwrap_or(image);
                let has_tag_or_digest = after_host.contains(':') || after_host.contains('@');
                if !has_tag_or_digest {
                    bad.push(format!("{}: {image}", path.display()));
                }
            }
        }
    }
    if bad.is_empty() {
        Outcome::Pass
    } else {
        Outcome::Fail(format!(
            "untagged image refs in production manifests: {bad:?}"
        ))
    }
}

/// C10 — every CRD declares `metadata.labels[app.kubernetes.io/name]`
/// (CNCF recommended-label convention).
pub fn check_recommended_labels(crds: &[&Value]) -> Outcome {
    let mut missing = Vec::new();
    for c in crds {
        let kind = crd_kind(c).unwrap_or("?");
        let label = c
            .get("metadata")
            .and_then(|m| m.get("labels"))
            .and_then(|l| l.get("app.kubernetes.io/name"))
            .and_then(Value::as_str);
        if label.is_none() {
            missing.push(kind.to_string());
        }
    }
    if missing.is_empty() {
        Outcome::Pass
    } else {
        Outcome::Fail(format!(
            "CRDs missing app.kubernetes.io/name label: {missing:?}"
        ))
    }
}

/// C11 — every CRD scopes itself (`Namespaced` or `Cluster`).
pub fn check_scope(crds: &[&Value]) -> Outcome {
    let mut missing = Vec::new();
    for c in crds {
        let kind = crd_kind(c).unwrap_or("?");
        let scope = c
            .get("spec")
            .and_then(|s| s.get("scope"))
            .and_then(Value::as_str);
        match scope {
            Some("Namespaced") | Some("Cluster") => {}
            _ => missing.push(kind.to_string()),
        }
    }
    if missing.is_empty() {
        Outcome::Pass
    } else {
        Outcome::Fail(format!("CRDs without valid scope: {missing:?}"))
    }
}

/// C12 — at least one printer column per CRD references either
/// `.status.conditions` or `.status.phase` (the canonical "what's
/// the operator-observed state?" surface).
pub fn check_state_printer_column(crds: &[&Value]) -> Outcome {
    let mut missing = Vec::new();
    for c in crds {
        let kind = crd_kind(c).unwrap_or("?");
        let mut found = false;
        for v in crd_versions(c) {
            let Some(cols) = v
                .get("additionalPrinterColumns")
                .and_then(Value::as_sequence)
            else {
                continue;
            };
            for col in cols {
                let Some(jp) = col.get("jsonPath").and_then(Value::as_str) else {
                    continue;
                };
                if jp.contains(".status.conditions") || jp == ".status.phase" {
                    found = true;
                    break;
                }
            }
            if found {
                break;
            }
        }
        if !found {
            missing.push(kind.to_string());
        }
    }
    if missing.is_empty() {
        Outcome::Pass
    } else {
        Outcome::Fail(format!(
            "CRDs without status-state printer column: {missing:?}"
        ))
    }
}

/// C13 — every Deployment runs as non-root with a seccomp profile.
pub fn check_pod_security_baseline(manifests: &BTreeMap<PathBuf, Vec<Value>>) -> Outcome {
    let mut bad = Vec::new();
    for docs in manifests.values() {
        for d in docs {
            if d.get("kind").and_then(Value::as_str) != Some("Deployment") {
                continue;
            }
            let name = d
                .get("metadata")
                .and_then(|m| m.get("name"))
                .and_then(Value::as_str)
                .unwrap_or("?")
                .to_string();
            let pod_sec = d
                .get("spec")
                .and_then(|s| s.get("template"))
                .and_then(|t| t.get("spec"))
                .and_then(|s| s.get("securityContext"));
            let runs_as_nonroot = pod_sec
                .and_then(|s| s.get("runAsNonRoot"))
                .and_then(Value::as_bool)
                == Some(true);
            let has_seccomp = pod_sec.and_then(|s| s.get("seccompProfile")).is_some();
            if !(runs_as_nonroot && has_seccomp) {
                bad.push(name);
            }
        }
    }
    if bad.is_empty() {
        Outcome::Pass
    } else {
        Outcome::Fail(format!(
            "Deployments missing runAsNonRoot or seccompProfile: {bad:?}"
        ))
    }
}

/// C14 — supply-chain CI rows are wired (cargo-deny, cosign-verify,
/// Trivy, npm audit). We assert by reading `.github/workflows/ci.yml`
/// and checking for the row markers — this catches accidental
/// row-removals in PR review.
pub fn check_supply_chain_rows() -> Outcome {
    let path = repo_root().join(".github/workflows/ci.yml");
    let Ok(text) = std::fs::read_to_string(&path) else {
        return Outcome::Fail(format!("cannot read {}", path.display()));
    };
    let required = [
        ("cargo-deny", "cargo deny check"),
        ("trivy", "aquasecurity/trivy-action"),
        ("npm-audit", "npm audit --audit-level=high"),
        ("cosign-verify", "cosign-verify"),
    ];
    let mut missing = Vec::new();
    for (label, marker) in required {
        if !text.contains(marker) {
            missing.push(label);
        }
    }
    if missing.is_empty() {
        Outcome::Pass
    } else {
        Outcome::Fail(format!("ci.yml missing rows: {missing:?}"))
    }
}

/// C15 — `deny.toml` is present at workspace root and configures
/// the four required cargo-deny sections.
pub fn check_deny_config() -> Outcome {
    let path = repo_root().join("deny.toml");
    let Ok(text) = std::fs::read_to_string(&path) else {
        return Outcome::Fail("deny.toml missing".into());
    };
    let required_sections = ["[advisories]", "[licenses]", "[bans]", "[sources]"];
    let mut missing: Vec<&str> = required_sections
        .iter()
        .filter(|s| !text.contains(*s))
        .copied()
        .collect();
    if missing.is_empty() {
        Outcome::Pass
    } else {
        missing.sort();
        Outcome::Fail(format!("deny.toml missing sections: {missing:?}"))
    }
}

/// Run every conformance criterion and return a populated report.
pub fn run_all_checks() -> ConformanceReport {
    let manifests = load_repo_manifests();
    let crds = collect_crds(&manifests);
    let mut report = ConformanceReport::default();
    let mut push = |id, criterion, outcome| {
        report.results.push(CheckResult {
            id,
            criterion,
            outcome,
        });
    };
    push(
        "C1",
        "Every CRD has a served + storage version",
        check_crd_versions_served(&crds),
    );
    push(
        "C2",
        "Every CRD has additional printer columns",
        check_printer_columns(&crds),
    );
    push(
        "C3",
        "Every CRD status declares a conditions[] array",
        check_conditions_array(&crds),
    );
    push(
        "C4",
        "Every CRD spec is a structural schema",
        check_structural_schema(&crds),
    );
    push(
        "C5",
        "Every CRD ships at least one CEL x-kubernetes-validations rule",
        check_cel_validations(&crds),
    );
    push(
        "C6",
        "Every CRD declares a status subresource",
        check_status_subresource(&crds),
    );
    push(
        "C7",
        "Every Deployment has liveness + readiness probes",
        check_deployment_probes(&manifests),
    );
    push(
        "C8",
        "Operator namespace has a default-deny NetworkPolicy",
        check_default_deny_netpol(&manifests),
    );
    push(
        "C9",
        "Every image ref declares an explicit tag or digest (no implicit :latest)",
        check_image_pinning(&manifests),
    );
    push(
        "C10",
        "Every CRD carries app.kubernetes.io/name label",
        check_recommended_labels(&crds),
    );
    push(
        "C11",
        "Every CRD declares a valid scope",
        check_scope(&crds),
    );
    push(
        "C12",
        "Every CRD exposes a status-state printer column",
        check_state_printer_column(&crds),
    );
    push(
        "C13",
        "Every Deployment runs non-root with a seccompProfile",
        check_pod_security_baseline(&manifests),
    );
    push(
        "C14",
        "ci.yml wires the supply-chain rows (cargo-deny, trivy, npm audit, cosign-verify)",
        check_supply_chain_rows(),
    );
    push(
        "C15",
        "deny.toml configures advisories/licenses/bans/sources",
        check_deny_config(),
    );
    report
}
