apiVersion: v1
kind: Namespace
metadata:
  name: azureclaw-system
  labels:
    app.kubernetes.io/name: azureclaw
    app.kubernetes.io/component: system
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
